# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        #Commente pour l'instant ?
        #in_memory:
        #    memory: ~
        users:
            entity: { class: AppBundle\Entity\Utilisateur, property: mail }


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - AppBundle\Security\LoginFormAuthenticator
            logout:
                path: /logout
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        #path est une expression reguliere

        # On restreint la visualisation des affaires aux utilisateurs qui se sont authentifies
        #- { path: 'Affaires', roles: ROLE_USER }
        # On restreint la gestion des visas aux personnes autorisees
        #- { path: 'Item', roles: ROLE_VISA }

    encoders:
        AppBundle\Entity\Utilisateur: bcrypt
