# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded

    role_hierarchy:
        #add ?_switch_user= and then the username of whoever you want to log in as.
        # permet de se connecter avec un autre type de compte pour voir ce qu'il voit
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN: [ROLE_GESTION_VISAS]
        ROLE_GESTION_VISAS: [ROLE_GESTION_DOCUMENTS]
        ROLE_GESTION_DOCUMENTS: [ROLE_USER]

        ROLE_EXTE: [ROLE_USER]

    providers:
        #Commente pour l'instant ?
        #in_memory:
        #    memory: ~
        users:
            entity: { class: AppBundle\Entity\Utilisateur, property: mail }


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - AppBundle\Security\LoginFormAuthenticator
            logout:
                path: /logout
            switch_user: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        #path est une expression reguliere

        # On restreint la visualisation des affaires aux utilisateurs qui se sont authentifies
        #- { path: 'Affaires', roles: ROLE_USER }
        # On restreint la gestion des visas aux personnes autorisees
        #- { path: 'Item', roles: ROLE_VISA }

    encoders:
        AppBundle\Entity\Utilisateur: bcrypt
