AppBundle\Entity\ItemsMateriel:
    type: entity
    table: items_materiel
    id: {  }
    fields:
        ensemble:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
                default: Autre
    oneToOne:
        idItem:
            targetEntity: Items
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_item:
                    referencedColumnName: id_item
            orphanRemoval: false
    lifecycleCallbacks: {  }
