AppBundle\Entity\Items:
    type: entity
    table: items
    indexes:
        lots_item_fk:
            columns:
                - id_lot
    id:
        idItem:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_item
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        nomItem:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: nom_item
    manyToOne:
        idLot:
            targetEntity: Lots
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_lot:
                    referencedColumnName: id_lot
            orphanRemoval: false
    lifecycleCallbacks: {  }
