AppBundle\Entity\ItemsPlans:
    type: entity
    table: items_plans
    id: {  }
    fields:
        etage:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
    oneToOne:
        idItem:
            targetEntity: Items
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_item:
                    referencedColumnName: id_item
            orphanRemoval: false
    lifecycleCallbacks: {  }
