AppBundle\Entity\Lots:
    type: entity
    table: lots
    indexes:
        noms_lots_lots_fk:
            columns:
                - id_nom_lot
        affaires_lots_fk:
            columns:
                - id_affaire
    id:
        idLot:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_lot
            generator:
                strategy: IDENTITY
    fields:
        numeroLot:
            type: smallint
            nullable: false
            options:
                unsigned: false
            column: numero_lot
    manyToOne:
        idAffaire:
            targetEntity: Affaires
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_affaire:
                    referencedColumnName: id_affaire
            orphanRemoval: false
        idNomLot:
            targetEntity: NomsLots
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_nom_lot:
                    referencedColumnName: id_nom_lot
            orphanRemoval: false
    lifecycleCallbacks: {  }
