AppBundle\Entity\Organismes:
    type: entity
    table: organismes
    id:
        idOrganisme:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_organisme
            generator:
                strategy: IDENTITY
    fields:
        nomOrganisme:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: nom_organisme
    lifecycleCallbacks: {  }
