AppBundle\Entity\TypesRemarque:
    type: entity
    table: types_remarque
    id:
        idTypeRemarque:
            type: smallint
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_type_remarque
            generator:
                strategy: IDENTITY
    fields:
        typeRemarque:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: type_remarque
    lifecycleCallbacks: {  }
